# This is a basic workflow to help you get started with Actions

name: node

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  schedule:
    - cron: '0 23 */3 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download_rss_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: download yaml latest from nodefree
      # Runs a set of commands using the runners shell
        id: step2
        run: |
          year=`date "+%Y"`
          month=`date "+%-m"`
          month2=`date "+%m"`
          day=`date "+%-d"`
          day2=`date "+%d"`
          clock=`date "+%Y%m%d%H%M%S"`
          echo "clock=$(($clock))" >> $GITHUB_OUTPUT
          # Other steps that change files in the repository
          mkdir -p node
          arr=(
            "https://nodefree.githubrowcontent.com/$year/$month2/$year$month2$day2.yaml,nodefree.yaml"
            "https://nodefree.githubrowcontent.com/$year/$month2/$year$month2$day2.txt,nodefree.txt"
            "https://raw.githubusercontent.com/fish2018/ClashForge/main/clash_config.yaml,clash_config_1.yaml"
            "https://raw.githubusercontent.com/tony0392/ClashForge/main/clash_config.yaml,clash_config_2.yaml"
            "https://raw.githubusercontent.com/gooooooooooooogle/collectSub/main/sub/$year/$month/$month-$day.yaml,gooooooooooooogle.yaml"
            "https://raw.githubusercontent.com/tagore-cai/proxy-sub/main/sub/$year/$month/$month-$day.yaml,collectSub.yaml"
          )
          echo "|||" > node/README.md
          echo "|-|-|" >> node/README.md
          for i in "${!arr[@]}"; do
            IFS=',' read -r url name <<< "${arr[i]}"
            curl -o "node/$name" "$url"
            echo "|$url|[`du -h node/$name`](https://raw.gitmirror.com/zx419d2o0/TasIkE/main/node/$name)|">>node/README.md
          done
          # sed -i '/^\s*#/d' node/nodefree.yaml

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message:  ${{ steps.step2.outputs.clock }} updated
          push_options: '--force'
