# This is a basic workflow to help you get started with Actions

name: tv/live/sport

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  migu_sports_job:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: run 7days_sports
        id: step2
        run: |
          clock=`date "+%Y%m%d%H%M%S"`
          echo "clock=$(($clock))" >> $GITHUB_OUTPUT
          cd tv/live
          ./7days_sports
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message:  ${{ steps.step2.outputs.clock }} updated
          push_options: '--force'
