# This is a basic workflow to help you get started with Actions

name: cat vod tv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get_tv_interface_job:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: download json and default first
        id: step2
        run: |
          clock=`date "+%Y%m%d%H%M%S"`
          arr=(
            https://github.moeyy.xyz/raw.githubusercontent.com/gaotianliuyun/gao/master/0825.json
            https://gitee.com/okjack/okk/raw/master/ok.txt
            http://xhww.fun/小米/DEMO.json
            http://我不是.肥猫.live/接口禁止贩卖
            http://ygbhbox.3vfree.club/pg/jsm.json
            )
          mkdir -p json
          rm json/*.log
          # curl -o json/dancang.json ${arr[0]}
          # echo "current   ${arr[0]}">json/$clock.log
          # for(( i=1;i<${#arr[@]};i++)) do
          #   echo "$i   ${arr[i]}">>json/$clock.log
          #   curl -o json/${i}.json ${arr[i]}
          # done
          for i in "${!arr[@]}";
          do
            curl -o json/$i.json ${arr[i]}
            echo "$i   ${arr[i]}">>json/$clock.log
          done
          echo "clock=$(($clock))" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message:  ${{ steps.step2.outputs.clock }} updated
          push_options: '--force'
